import type { Metadata } from "next";
import { Schibsted_Grotesk } from 'next/font/google';
import { Roboto } from "next/font/google";
import localFont from 'next/font/local';

import "./globals.css";

const roboto = Roboto({
  weight:['200'],
  subsets:['latin'],
  variable:'--font-roboto',
});

const schibsted = Schibsted_Grotesk({
  weight: ['400', '600', '500'],
  subsets: ['latin'],
  variable: '--font-schibsted',
});

const camptonBold = localFont({
  src: '../public/fonts/CamptonBold.woff',
  weight: '700',
  style: 'normal',
  variable: '--font-campton-bold', 
});

const camptonMedium = localFont({
  src: '../public/fonts/CamptonMedium.woff',
  weight: '500',
  style: 'normal',
  variable: '--font-campton-medium',
});

const camptonBook = localFont({
  src: '../public/fonts/CamptonBook.woff',
  weight: '400',
  style: 'normal',
  variable: '--font-campton-book',
});

const camptonSemiBold = localFont({
  src: '../public/fonts/CamptonSemiBold.woff',
  weight: '600',
  style: 'normal',
  variable: '--font-campton-semibold',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${schibsted.variable} ${camptonMedium.variable} ${camptonBold.variable} ${camptonBook.variable} ${camptonSemiBold.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
